VMarket/VMarket/Controllers/CitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VMarket.Classes;
using VMarket.Models;

namespace VMarket.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CitiesController : Controller
    {
        private VMarketContext db = new VMarketContext();

        // GET: Cities
        public ActionResult Index()
        {
            var cities = db.Cities.Include(c => c.Department);
            return View(cities.ToList());
        }

        // GET: Cities/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // GET: Cities/Create
        public ActionResult Create()
        {

            

            var Department = ComboxHelper.GetDepartment();
            ViewBag.DepartmentId = new SelectList(Department, "DepartmentId", "Name");
            return View();
        }

        // POST: Cities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CityId,Name,DepartmentId")] City city)
        {
            if (ModelState.IsValid)
            {
                db.Cities.Add(city);
                db.SaveChanges();
                return RedirectToAction("Index");
            }


            var Department = ComboxHelper.GetDepartment();
            ViewBag.DepartmentId = new SelectList(Department, "DepartmentId", "Name");
            return View(city);
        }

        // GET: Cities/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            var Department = ComboxHelper.GetDepartment();
            ViewBag.DepartmentId = new SelectList(Department, "DepartmentId", "Name");
            return View(city);
        }

        // POST: Cities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CityId,Name,DepartmentId")] City city)
        {
            if (ModelState.IsValid)
            {
                db.Entry(city).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            var Department = ComboxHelper.GetDepartment();
            ViewBag.DepartmentId = new SelectList(Department, "DepartmentId", "Name");
            return View(city);
        }

        // GET: Cities/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // POST: Cities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            City city = db.Cities.Find(id);
            db.Cities.Remove(city);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VMarket/VMarket/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VMarket.Models;

namespace VMarket.Controllers
{
    public class OrdersController : Controller
    {
        private VMarketContext db = new VMarketContext();

        // GET: Orders
        public ActionResult Index()
        {
            var user = db.Users.Where(u => u.UserName == User.Identity.Name).FirstOrDefault();
            if (User.IsInRole("User"))
            {
                var order = db.Orders.Where(o => o.UserId == user.UserId).Include(o => o.User).ToList();
                foreach (var orders in order) { 
                    orders.State = db.States.Where(s => s.StateId == orders.StateId).FirstOrDefault(); 
                }
                return View(order);
            }
            else  {
                var order = db.Orders.ToList();
                foreach (var orders in order)
                {
                    orders.State = db.States.Where(s => s.StateId == orders.StateId).FirstOrDefault();
                }
                return View(order);
            }
        }

        // GET: Orders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // GET: Orders/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OrderId,Fecha,StateId,UserId")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Orders.Add(order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(order);
        }

        // GET: Orders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OrderId,Fecha,StateId,UserId")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(order);
        }

        // GET: Orders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.Orders.Find(id);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VMarket/VMarket/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - VMARKET</title>
    @Styles.Render("~/Content/css")
    
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Simple Dashboard</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <meta name="layout" content="main" />

    <script type="text/javascript" src="http://www.google.com/jsapi"></script>

    <script src="~/Content/js/jquery/jquery-1.8.2.min.js" type="text/javascript"></script>
    <link href="~/Content/css/customize-template.css" type="text/css" media="screen, projection" rel="stylesheet" />

    <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,200,300,700,600' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400,700,300' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,100' rel='stylesheet' type='text/css'>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="~/Content/css/owl.carousel.css">
    <link rel="stylesheet" href="~/Content/css/styles.css">
    <link rel="stylesheet" href="~/Content/css/responsive.css">


    <style>
        #body-content {
            padding-top: 40px;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <button class="btn btn-navbar" data-toggle="collapse" data-target="#app-nav-top-bar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="~/Home/index" class="brand"><i class="icon-leaf">Virtual Market</i></a>
                <div id="app-nav-top-bar" class="nav-collapse">
                    <ul class="nav navbar-nav" style="font-weight:bold;">
                       @if (!User.IsInRole("Admin"))
                       {
                         <li>@Html.ActionLink("Comprar", "Create", "OrderDetails")</li>
                        <li>@Html.ActionLink("Mis Ordenes", "Index", "Orders")</li>
                       }
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Administracion Panel<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Departamento", "Index", "Departments")</li>
                                    <li>@Html.ActionLink("Ciudad", "Index", "Cities")</li>
                                    <li>@Html.ActionLink("Categria", "Index", "Categories")</li>
                                    <li>@Html.ActionLink("Empresa", "Index", "Companies")</li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Compras<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Comprar", "Create", "OrderDetails")</li>
                                    <li>@Html.ActionLink("Ordenes", "Index", "Orders")</li>
                                    <li>@Html.ActionLink("Producto", "Index", "Products")</li>
                                </ul>
                            </li>
                                <li>@Html.ActionLink("Informes", "Index", "Orders")</li>
                        }
                    </ul>

                        @Html.Partial("_LoginPartial")
</div>
            </div>
        </div>
    </div>

  

    <script src="~/Content/js/bootstrap/bootstrap-transition.js" type="text/javascript"></script>
    <script src="~/Content/js/bootstrap/bootstrap-alert.js" type="text/javascript"></script>
    <script src="~/Content/js/bootstrap/bootstrap-modal.js" type="text/javascript"></script>
    <script src="~/Content/js/bootstrap/bootstrap-dropdown.js" type="text/javascript"></script>
    <script src="~/Content/js/bootstrap/bootstrap-scrollspy.js" type="text/javascript"></script>
    <script src="~/Content/js/bootstrap/bootstrap-tab.js" type="text/javascript"></script>
    <script src="~/Content/js/bootstrap/bootstrap-tooltip.js" type="text/javascript"></script>
    <script src="~/Content/js/bootstrap/bootstrap-popover.js" type="text/javascript"></script>
    <script src="~/Content/js/bootstrap/bootstrap-button.js" type="text/javascript"></script>
    <script src="~/Content/js/bootstrap/bootstrap-collapse.js" type="text/javascript"></script>
    <script src="~/Content/js/bootstrap/bootstrap-carousel.js" type="text/javascript"></script>
    <script src="~/Content/js/bootstrap/bootstrap-typeahead.js" type="text/javascript"></script>
    <script src="~/Content/js/bootstrap/bootstrap-affix.js" type="text/javascript"></script>
    <script src="~/Content/js/bootstrap/bootstrap-datepicker.js" type="text/javascript"></script>
    <script src="~/Content/js/jquery/jquery-tablesorter.js" type="text/javascript"></script>
    <script src="~/Content/js/jquery/jquery-chosen.js" type="text/javascript"></script>
    <script src="~/Content/js/jquery/virtual-tour.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(function() {
            $('#sample-table').tablesorter();
            $('#datepicker').datepicker();
            $(".chosen").chosen();
        });
    </script>





            <div class="container body-content">
                @RenderBody()
                <hr />
                <footer>
                    <p>&copy; @DateTime.Now.Year - VirtualMarket - Juan Penagos Mejia - Juanpenagoss@hotmail.com</p>
                </footer>
            </div>

            @Scripts.Render("~/bundles/jquery")
            @Scripts.Render("~/bundles/bootstrap")
            @RenderSection("scripts", required: false)
</body>
</html>